spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
#    url: jdbc:postgresql://localhost:5432/user_db !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  cache:
    type: redis

  data:
    redis:
      host: redis
#      host: localhost !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      port: 6379
      timeout: 60000

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000

server:
  port: 8081