spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/user_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
