name: User Service CI Pipeline

on:
  push:
    branches: [ main, feature/user-service-testing-containerization-ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: 🔹 Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run unit tests
        run: mvn -Dtest=**/*ImplTest test

  integration-tests:
    name: 🔸 Run Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run integration tests
        run: mvn -Dtest=**/*IntegrationTest verify
